# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

FROM nvcr.io/nvidia/base/ubuntu:22.04_20240212

#
# Install any utils needed for execution
#
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    bc \
    bzip2 \
    can-utils \
    ca-certificates \
    gnupg2 \
    gstreamer1.0-alsa \
    gstreamer1.0-libav \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-tools \
    i2c-tools \
    iw \
    kbd \
    kmod \
    language-pack-en-base \
    libcanberra-gtk3-module \
    libdrm-dev \
    libgles2 \
    libglvnd-dev \
    libgtk-3-0 \
    libpython2.7 \
    libudev1 \
    libvulkan1 \
    libzmq5 \
    mtd-utils \
    parted \
    pciutils \
    python-is-python3 \
    python3 \
    python3-pexpect \
    python3-distutils \
    python3-numpy \
    sox \
    udev \
    vulkan-tools \
    wget \
    wireless-tools wpasupplicant \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean


#
# Configure nvidia apt repo
#
ARG RELEASE
RUN wget -P /etc/apt/trusted.gpg.d https://repo.download.nvidia.com/jetson/jetson-ota-public.asc
RUN wget -P /etc/apt/preferences.d https://repo.download.nvidia.com/jetson/nvidia-repo-pin-600
RUN echo "deb https://repo.download.nvidia.com/jetson/common ${RELEASE} main" >> /etc/apt/sources.list.d/nvidia-l4t-apt-source.list

#
# Install cuda-toolkit-12-6, cuda-libraries-12-6, and cuda-compat-12-6 for CUDA developer packages
# Install cuda-libraries-12-6 and cuda-compat-12-6 if need CUDA runtime only
#
RUN apt-get update && apt-get install -y --no-install-recommends \
    cuda-toolkit-12-6 cuda-libraries-12-6 \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN apt-get update && apt-get download cuda-compat-12-6 \
    && dpkg-deb -R ./cuda-compat-12-6_*_arm64.deb ./cuda-compat \
    && cp -r ./cuda-compat/usr/local/* /usr/local/ \
    && rm -rf ./cuda-compat-12-6_*_arm64.deb ./cuda-compat

#
# Install nvidia-cudnn-dev for CuDNN developer packages
# Use nvidia-cudnn if need CuDNN runtime only
#
RUN apt-get update && apt-get install -y --no-install-recommends \
    nvidia-cudnn-dev \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

#
# Install nvidia-tensorrt-dev for TensorRT developer packages
# Use nvidia-tensorrt if need TensorRT runtime only
#
RUN apt-get update && apt-get install -y --no-install-recommends \
    nvidia-tensorrt-dev \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

#
# Install nvidia-vpi-dev for VPI developer packages
# Use nvidia-vpi if need VPI runtime only
#
RUN mkdir -p /lib/firmware/
RUN apt-get update && apt-get install -y --no-install-recommends \
    nvidia-vpi-dev \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

#
# Install nvidia-opencv-dev for OpenCV developer packages
# Use nvidia-opencv if need OpenCV runtime only
#
RUN apt-get update && apt-get install -y --no-install-recommends \
    nvidia-opencv-dev \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

#
# Install Multimedia API samples & libs
#
RUN apt-get update && apt-get download nvidia-l4t-jetson-multimedia-api \
    && dpkg-deb -R ./nvidia-l4t-jetson-multimedia-api_*_arm64.deb ./mm-api \
    && cp -r ./mm-api/usr/src/jetson_multimedia_api /usr/src/jetson_multimedia_api \
    && sed -i 's/sudo//' ./mm-api/DEBIAN/postinst \
    && ./mm-api/DEBIAN/postinst \
    && rm -rf ./nvidia-l4t-jetson-multimedia-api_*_arm64.deb ./mm-api

#
# Install DLA compiler
#
RUN apt-get update && apt-get download nvidia-l4t-dla-compiler \
    && dpkg-deb -R ./nvidia-l4t-dla-compiler_*_arm64.deb ./dla \
    && cp -r ./dla/usr/lib/* /usr/lib/ \
    && rm -rf ./nvidia-l4t-dla-compiler_*_arm64.deb ./dla

#
# Install GStreamer
#
RUN apt-get update && apt-get download nvidia-l4t-gstreamer \
    && dpkg-deb -R ./nvidia-l4t-gstreamer_*_arm64.deb ./gstreamer \
    && cp -r ./gstreamer/usr/bin/* /usr/bin/ \
    && cp -r ./gstreamer/usr/lib/* /usr/lib/ \
    && rm -rf ./nvidia-l4t-gstreamer_*_arm64.deb ./gstreamer

#Update libraries
RUN ldconfig

#
# Setup environment variables
#
ENV CUDA_HOME="/usr/local/cuda"
ENV PATH="/usr/local/cuda/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"

RUN echo "/usr/lib/aarch64-linux-gnu/tegra" >> /etc/ld.so.conf.d/nvidia-tegra.conf && \
    echo "/usr/lib/aarch64-linux-gnu/tegra-egl" >> /etc/ld.so.conf.d/nvidia-tegra.conf

RUN rm /usr/share/glvnd/egl_vendor.d/50_mesa.json
RUN mkdir -p /usr/share/glvnd/egl_vendor.d/ && echo '\
{\
    "file_format_version" : "1.0.0",\
    "ICD" : {\
        "library_path" : "libEGL_nvidia.so.0"\
    }\
}' > /usr/share/glvnd/egl_vendor.d/10_nvidia.json

RUN mkdir -p /usr/share/egl/egl_external_platform.d/ && echo '\
{\
    "file_format_version" : "1.0.0",\
    "ICD" : {\
        "library_path" : "libnvidia-egl-wayland.so.1"\
    }\
}' > /usr/share/egl/egl_external_platform.d/nvidia_wayland.json

RUN ldconfig

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all

# Clean up link to nvidia repo
RUN rm /etc/apt/sources.list.d/nvidia-l4t-apt-source.list
RUN rm /etc/apt/preferences.d/nvidia-repo-pin-600
RUN rm /etc/apt/trusted.gpg.d/jetson-ota-public.asc
